### ISSUE TITLE
Method for checking if over limit w/o updating

### ISSUE THREAD

**Issue by ctoomey** [mokies/ratelimitj#1]
Hi, your library looks great, with the best-of-breed sliding window algorithm and the pluggable backends!

I've got a use case that it doesn't support very well though, where I need to check if the limit has been reached without incrementing it if not. We're going to track login failures, and once we've reached the limit, disallow further login attempts. So we first need to check if the failure rate has reached limit, and only then allow the request and increment the count if it fails.

So I'm thinking of adding another method to RequestRateLimiter to enable this, say

```java
    /**
     * Determine if the given key, after incrementing by the given weight, is &gt;= the configured rate limit.
     * @param key key.
     * @param weight A variable weight.
     * @return {@code true} if the key is &gt;== the limit, otherwise {@code false} .
     */
    boolean geLimit(String key, int weight);
```

Looking at the implementation code, this would be easily implemented since it's a slight variant of the existing code for overlimit().

Would you be open to a pull request if I add this?

thx,
Chris

**Comment by mokies** [comment]
HI Chris,

Thanks for taking the time to write up your suggestion for a pull request. 

I would most definitely be happy to accept this pull request. An incorrect password attempt count seems to be a common scenario that people are looking for the library to support.

Cheers,
Craig

**Comment by mokies** [comment]
Thanks Chris - I've taken a look at your changes and they look good, appreciate the effort. I should get some time this weekend to add a few more tests and merge in your branch.

Cheers,
Craig

**Comment by ctoomey** [comment]
Great, thanks Craig. I'd originally thought to add an ```atLimit(key)``` function which would only check the limit, but realized that I also needed a function that would take a key and a weight, store the hit if the limit wasn't exceeded, and return whether the limit was met or exceeded. I realized I that a single function that did the latter would suffice since it could be passed 0 as weight to achieve the former. Hence ```geLimit(key, weight)```.

**Comment by ctoomey** [comment]
Craig, thanks for merging my pull request. Will you publish version 0.3.4 with the changes to maven soon so I can use that instead of my local build? Thanks

**Comment by mokies** [comment]
I will push out a 4.0-RC over the weekend as I'm going to change some of the method names to better communicate the action.

**Comment by mokies** [comment]
0.4.0.M1 release to maven central and should be available in a few hours.

**Comment by ctoomey** [comment]
Thanks, I've updated to use that and all is well. Much appreciated!
