### ISSUE TITLE
io.lettuce.core.RedisCommandExecutionException: ERR unknown command 'SCRIPT'

### ISSUE THREAD

**Issue by fsamir** [mokies/ratelimitj#11]
Hi there,

I am getting the following error, when ratelimitj tries to load the lua script.

`io.lettuce.core.RedisCommandExecutionException: ERR unknown command 'SCRIPT'`

Redis version 3.2.11
ratelimitj-redis:04.1

**Comment by mokies** [comment]
Are you able to verify from the redis-cli that the script command is available?

Wast the commend renamed or is SCRIPT not available in the version you are using (3.2 does support SCRIPT)?

**Comment by mokies** [comment]
Fixed in commit https://github.com/mokies/ratelimitj/commit/fff28832d923d94a78cccfcb4803fd7f89ea331c and will be included in the next release

**Comment by mokies** [comment]
https://github.com/mokies/ratelimitj/releases/tag/v0.4.4
