### ISSUE TITLE
is requestLimitRules really needed at the time of RedisSlidingWindowRequestRateLimiter creation?

### ISSUE THREAD

**Issue by Meyy-DL** [mokies/ratelimitj#14]
Thank you for all your hard work. Am trying to include your work and realized we must have _requestLimitRules_ in hand before we create _RedisSlidingWindowRequestRateLimiter_ instance. I would like to create vanilla _RedisSlidingWindowRequestRateLimiter_ instance during application startup and inject different rules at different point in the process.

So I was looking at your code and thinking whether we can create vanilla/generic _RedisSlidingWindowRequestRateLimiter_ without tying to limit rules and expose public method to pass in serialized rules later when needed?

Something like 
`public RedisSlidingWindowRequestRateLimiter(StatefulRedisConnection<String, String> connection)`

Highly appreciate your thoughts on my approach.

**Comment by mokies** [comment]
You should be able to use `RedisRateLimiterFactory` for this purpose. I have used `RedisRateLimiterFactory` in the dropwizard module to dynamically create instances of `RedisSlidingWindowRequestRateLimiter`.  While `RedisRateLimiterFactory` is fairly lightweight to construct the `RedisRateLimiterFactory` has a small internal cache of instances should this be a concern.

**Comment by Meyy-DL** [comment]
Looking at the implementation, I guess thats what I was looking for. It would be nice to document these use cases somewhere for future reference. Thanks @mokies!
