### ISSUE TITLE
Unusual current rate limit conditions sometimes occur

### ISSUE THREAD

**Issue by shengnian** [mokies/ratelimitj#16]
This is a great project，But I have encountered some problems in use it, i change `ReidsClient`  to `RedisClusterClient`  and 'StatefulRedisConnection' and to `StatefulRedisClusterConnection`, such as below code: 

```
    RedisClusterClient client = RedisClusterClient.create(getRedisUri(properties.getRedisCluster())); 
     GenericObjectPool<StatefulRedisClusterConnection<String, String>> pool = ConnectionPoolSupport
         .createGenericObjectPool(() -> client.connect(), new GenericObjectPoolConfig());
 
     try {
       StatefulRedisClusterConnection<String, String> connection = pool.borrowObject()
Set<RequestLimitRule> rules = Collections.singleton(RequestLimitRule.of(1, TimeUnit.SECONDS, 1000).withPrecision(2));
```
Occasionally, the current limit will occur. I have determined that the maximum flow rate has not been reached. It often happens around 1 second，my question is why and how to fix it ? thanks. 

the server env:
```
Redis Cluster:  3.x   (3 master and 3 slave)
CentOS 7.x
```

**Comment by mokies** [comment]
Thanks for the feedback. I haven't tested the library against a cluster Redis configuration. I will address this in the next point release.

**Comment by mokies** [comment]
I note that you have set the Limiter rule to precision 2 which might not do what you expect. The precision maybe impacting your results.
