### ISSUE TITLE
The library fails to handle a missing script

### ISSUE THREAD

**Issue by bsideup** [mokies/ratelimitj#20]
Hi!

We use RateLimitJ with AWS ElastiCache. Today we had an outage because AWS ElastiCache performed a maintenance and for some reason (we're going to check with AWS guys as well) the Lua scripts disappeared.
We started getting this error:
```
NOSCRIPT No matching script. Please use EVAL.
```

Would be great if the library will handle it gracefully and re-upload the scripts if they're missing.
I assume this is easy to test by uploading the scripts, running `FLUSHALL` and then attempting to apply the rate limiting. 
Shameless plug: you can use http://github.com/testcontainers/testcontainers-java to test that ☺️

**Comment by ofirnk** [comment]
From a neighbouring project ;)
https://github.com/gresrun/jesque/pull/143

**Comment by mokies** [comment]
Thanks for your patience this is now fixed https://github.com/mokies/ratelimitj/commit/fff28832d923d94a78cccfcb4803fd7f89ea331c and will be included in the next release.

**Comment by mokies** [comment]
https://github.com/mokies/ratelimitj/releases/tag/v0.4.4
