### ISSUE TITLE
InMemory rate limiter changes pushed to Maven Central

### ISSUE THREAD

**Issue by cosimo** [mokies/ratelimitj#30]
Would it be possible to get the latest changes onto maven central?
I'm particularly interested in the in-memory rate limiter ones.
Thanks,

**Comment by mokies** [comment]
I have published the release to maven central and it should be available shortly

https://mvnrepository.com/artifact/es.moki.ratelimitj/ratelimitj-inmemory/0.6.0

**Comment by cosimo** [comment]
Thanks!
