### ISSUE TITLE
Dropwizard 2.X Support

### ISSUE THREAD

**Issue by RoiEXLab** [mokies/ratelimitj#38]
Hi, we're using ratelimitj for quite a while now and right now it's the only thing keeping us from uprading to dropwizard 2.0.
Are there any plans to support it in the near future?
Thanks

**Comment by mokies** [comment]
DW 2.0 support now available in [0.7.0-RC1](https://github.com/mokies/ratelimitj/releases/tag/0.7.0-RC1)
