### ISSUE TITLE
Outdated reactor-core version

### ISSUE THREAD

**Issue by roma0297** [mokies/ratelimitj#51]
I'm using Ratelimitj with my Spring Boot application. In Spring Boot I use `spring-boot-starter-webflux:2.4.1` and it requires `io.projectreactor:reactor-core`. The problem is that `ratelimitj-redis:0.7.0-RC3` needs `reactor-core:3.3.8.RELEASE` and `spring-boot-starter-webflux:2.4.1` needs `reactor-core:3.4.1` and there are some breaking changes between these 2 versions.

To be more specific I'm getting the following error: `java.lang.NoSuchMethodError: 'reactor.core.publisher.Flux reactor.core.publisher.Flux.retry(long, java.util.function.Predicate)'` in `RedisSlidingWindowRequestRateLimiter.java:139`. I think the error is quite self-explanatory.

@igorbolic already created a PR in which he fixes the problem: https://github.com/mokies/ratelimitj/pull/50

@mokies any chance to merge it anytime soon and publish a new release?

Thanks in advance!

**Comment by mokies** [comment]
Apologies again to anyone this issue blocked for so long. New release addresses this.
